GMAIL_USERNAME: 'sybandtest@gmail.com'
GMAIL_PASSWORD: 'omgsybandwtf'
CANONICAL_HOST: 'syband.herokuapp.com'
AUTH_TWITTER_KEY: '7sM63iIXgkwlHLKxjJxXCpBdg'
AUTH_TWITTER_SECRET: '4DYUwuodCF9pJeWjtVmlYywJEAZUoQSG8rz2znfE5iLnqqjEdH'
AUTH_GOOGLE_KEY: '614378359628-qosc1onjrd80vkbkm6s802jukaaadqfe.apps.googleusercontent.com'
AUTH_GOOGLE_SECRET: 'MX10Ck9KYlCuNfAFqNNcr0x7'
AUTH_FACEBOOK_KEY: '765709983472880'
AUTH_FACEBOOK_SECRET: '6e96984fcdfc3621de89e18ec78822c5'
AUTH_LINKEDIN_KEY: '774uf4is1jk2sq'
AUTH_LINKEDIN_SECRET: 'xsqwc1pUPqYetumB'
AUTH_SPOTIFY_KEY: 'b369a074ee9d4701ba37472e1b94817c'
AUTH_SPOTIFY_SECRET: '788c6e3fb5be48e3967e73f081727f8a'